apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-processor-7935
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-processor-7935
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
